import {browse, codeView, worldManagement, expectProperty} from './helpers.js';
import {test,expect,run} from './helpers.js';

test('sandbox keeps independent drafts, keeps independent world state, skips grading, and survives refresh',async ({page})=>{
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('/'); await expect(page.locator('#runButton')).toBeEnabled();
  await browse(page);await page.locator('#lessonNav button').filter({hasText:'Objects are the world'}).click();
  const training='player:tell("My training draft");';
  await codeView(page);await page.locator('#codeEditor').fill(training);
  await page.locator('#workspaceMode').selectOption('sandbox');
  await expect(page.locator('.rail')).toBeHidden();
  await expect(page.locator('.lesson-pane')).toBeHidden();
  await expect(page.locator('#editorPanel')).toBeVisible();
  await expect(page.locator('#worldPanel')).toBeVisible();
  const editor=await page.locator('#editorPanel').boundingBox(), world=await page.locator('#worldPanel').boundingBox();
  expect(editor.x+editor.width).toBeLessThanOrEqual(world.x+1);
  const code='o=create($room); o.name="Sandbox room"; player:tell(o); return o;';
  await run(page,code,'Return: #43');
  await expect(page.locator('#output')).toContainText('Execution completed.');
  await expect(page.locator('#output')).not.toContainText('Objective');
  await expect(page.locator('.world-status')).toContainText('8 objects');
  await expect(page.locator('.world-created')).toContainText('Sandbox room');
  await page.screenshot({path:'test-results/sandbox-desktop.png',fullPage:true});
  await page.locator('#workspaceMode').selectOption('training');
  await expect(page.locator('#codeEditor')).toHaveValue(training);
  await expect(page.locator('#progressText')).toHaveText('0 / 21 LESSONS');
  await expect(page.locator('#lessonTitle')).toHaveText('Objects are the world');
  await run(page,'return valid(#43);','Return: 0');
  await page.locator('#workspaceMode').selectOption('sandbox');
  await expect(page.locator('#codeEditor')).toHaveValue(code);
  await page.reload(); await expect(page.locator('#runButton')).toBeEnabled();
  await expect(page.locator('#workspaceMode')).toHaveValue('sandbox');
  await expect(page.locator('#codeEditor')).toHaveValue(code);
  await run(page,'return #43.name;','Return: "Sandbox room"');
  await page.locator('#runtimeProfileSelect').selectOption('lambdamoo');
  await expect(page.locator('#runButton')).toBeEnabled();
  await expect(page.locator('#codeEditor')).not.toHaveValue('return #43.name;');
  await run(page,'return valid(#43);','Return: 0');
  await page.locator('#runtimeProfileSelect').selectOption('toaststunt');
  await expect(page.locator('#runButton')).toBeEnabled();
  await expect(page.locator('#codeEditor')).toHaveValue('return #43.name;');
});
test('sandbox uses tabs on small screens and returns to split view when widened',async ({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/'); await expect(page.locator('#runButton')).toBeEnabled();
  await page.locator('#workspaceMode').selectOption('sandbox');
  await expect(page.locator('#editorPanel')).toBeVisible();
  await expect(page.locator('#worldPanel')).toBeHidden();
  await expect(page.locator('.rail')).toBeHidden();
  await page.getByRole('tab',{name:'World',exact:true}).click();
  await expect(page.locator('#worldPanel')).toBeVisible();
  await expect(page.locator('#editorPanel')).toBeHidden();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/sandbox-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await expect(page.locator('#editorPanel')).toBeVisible();
  await expect(page.locator('#worldPanel')).toBeVisible();
  await page.getByRole('tab',{name:'Code',exact:true}).focus();
  await page.keyboard.press('End');
  await expect(page.getByRole('tab',{name:'Reference',exact:true})).toBeFocused();
  await expect(page.locator('#referencePanel')).toBeVisible();
  await expect(page.locator('#worldPanel')).toBeVisible();
});
test('world shows the intended root classes and inherited tell without system properties on rooms',async ({page})=>{
  await page.goto('/'); await expect(page.locator('#runButton')).toBeEnabled();
  await page.getByRole('tab',{name:'World',exact:true}).click();
  await expect(page.locator('[data-property="room"]')).toHaveCount(0);
  await expect(page.locator('#worldDetail')).toContainText('#3 — Generic Room');
  await page.locator('#worldSearch').fill('#7');
  await page.locator('#worldTree [data-object-id="7"]').click();
  await expect(page.locator('[data-verb="tell notify"]')).toContainText('#6 — Generic Player');
  await page.locator('#worldSearch').fill('#0');
  await page.locator('#worldTree [data-object-id="0"]').click();
  await expect(page.locator('[data-property="room"]')).toContainText('#3 — Generic Room');
  await expect(page.locator('#worldDetail')).toContainText('#1 — Root Class');
});
